### ISSUE TITLE
user accounts

### ISSUE THREAD

**Issue by kamishirorui** [enstars/ensemble-square#2]

**Comment by mgn-yuuki** [comment]
Likely using Firebase Auth
https://firebase.google.com/docs/auth?authuser=0

Feature ideas:
- [ ] saving cards
- [ ] bookmarks

**Comment by mgn-yuuki** [comment]
Basic implementation done:
- Using Google sign in for simplicity
- @myang5 helped set up React Context for user object around the app #8

**Comment by yuuukun** [comment]
....5 months later update (holy fuck); database syncing is finally done, users can now add a name, username, game server/region, and dark/light mode. added another context (UserDataProvider) which i might just combine with AuthProvider later bc it really is just the same thing

**Comment by yuuukun** [comment]
future improvements 
- [ ] twitter sign-in
- [ ] discord sign-in
- [ ] combine userdata into one react context
